// <auto-generated />
using DiecastStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiecastStore.DataAccess.Migrations
{
    [DbContext(typeof(DiecastStoreDbContext))]
    [Migration("20250831075253_AddItemFkCarBrand")]
    partial class AddItemFkCarBrand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiecastStore.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarBrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBrandName = "Porsche",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CarBrandName = "Mercedes-Benz",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CarBrandName = "Audi",
                            DisplayOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CarBrandName = "Volkswagen",
                            DisplayOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CarBrandName = "Opel",
                            DisplayOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CarBrandName = "BMW",
                            DisplayOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CarBrandName = "Renault",
                            DisplayOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CarBrandName = "Peugeot",
                            DisplayOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CarBrandName = "Citroën",
                            DisplayOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CarBrandName = "Aston Martin",
                            DisplayOrder = 10
                        });
                });

            modelBuilder.Entity("DiecastStore.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBrandId = 1,
                            Description = "Mattel Hot Wheels 1989 Porsche 944 Turbo, Porsche Series 3/6 [Black]",
                            Name = "89' Porsche 944 Turbo",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 2,
                            CarBrandId = 2,
                            Description = "Hot Wheels '89 Mercedes Benz 560 Sec AMG, HW Turbo 4/5 [Black] 150/250",
                            Name = "'89 Mercedes-Benz 560 Sec AMG",
                            Price = 6.8399999999999999
                        },
                        new
                        {
                            Id = 3,
                            CarBrandId = 7,
                            Description = "Hot Wheels Renault Sport R.S. 01, HW Turbo 3/5 [red] 134/250",
                            Name = "Renault Sport R.S. 01'",
                            Price = 6.29
                        });
                });

            modelBuilder.Entity("DiecastStore.Models.Item", b =>
                {
                    b.HasOne("DiecastStore.Models.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("CarBrand");
                });
#pragma warning restore 612, 618
        }
    }
}
